schema_version = "1.0.0"

id = "osci_render"
version = "1.0.3"
name = "osci-render"
tagline = "Addon to send gpencil frames over to osci-render"
maintainer = "James H. Ball <https://github.com/jameshball>"
type = "add-on"

website = "https://github.com/jameshball/osci-render"

tags = ["Animation", "Bake", "Grease Pencil", "Import-Export", "Render"]

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]